### ISSUE TITLE
Sanity System

### ISSUE THREAD

**Issue by inkompotato** [100unity/InSaneSurvival#31]
sanity level 0-100%

- [x] influenced by Hunger, Thirst, HP
- [x] spawn monsters based on level
- [x] triggering visual effects
- [x] add camera filter/effect (also permanent effects)
- [x] more logic: malus on mob kills?
- [x] triggering audio effects

**Comment by SamuelllG** [comment]
- spawn more monsters the higher the insanity
- (insanity) mobs should be on client side --> other players don't see them
- despawn insanity mobs when out of range (--> since they are clientside, it doesn't make sense to contain them when the player can't see them)

**Comment by SamuelllG** [comment]
HOW TO: spawn mobs individually for each player and others can't see them

**Comment by SamuelllG** [comment]
points to clarify:
- how to spawn mobs in general: random?, or manually put them in scene (--> respawn?)
--> we probably need some kind of spawner functionality

- the longer changeRate is negative, the higher/lower it gets??

**Comment by SamuelllG** [comment]
thought about normalizing the severities, but doesn't really make sense because you'd have to use constants inside the code... without it you can at least see what your value does

**Comment by SamuelllG** [comment]
To add:
- apply sanity malus on mob kill (only if you kill "good" mobs, not if you're attacked?)
- maybe then we can also implement that you lose health when you're low on hunger thirst
