### ISSUE TITLE
NPC - Lifecycle

### ISSUE THREAD

**Issue by DavidPgl** [100unity/InSaneSurvival#44]
- [x] Respawning
- [x] Area-Respawn
- [x] Dying

**Comment by SamuelllG** [comment]
area, number of mobs --> empty gameobject with radius, number of mobs to spawn and probability --> prefab
probability for respawn
check for player near and skip spawn if near

**Comment by SamuelllG** [comment]
for random spawn point on navmesh reuse stuff from enemy random wandering
