### ISSUE TITLE
Crafting/Inventory - When crafting, the amount of items removed from the inventory doesn't work.

### ISSUE THREAD

**Issue by thuemmels** [100unity/InSaneSurvival#67]
The count on the buttons is correct, but when you check the inventory in the editor you can see that something went wrong (for example, one recipe needed 3 stone and 2 wood. The button counts decreased correctly, but in the editor inventory only one of each has been removed. This allows crafting even when the inventoryUI is empty.)

**Comment by DavidPgl** [comment]
Fixed
