### ISSUE TITLE
Camera - Control / FOV / Distance

### ISSUE THREAD

**Issue by Kaes3kuch3n** [100unity/InSaneSurvival#8]
Camera movement with the new input system

**Comment by inkompotato** [comment]
TODO: make rotation framerate independent
Edit: Issue seems to only occur on with vsync enabled (it is possible that this is only the case on gsync monitors)

**Comment by inkompotato** [comment]
Update: The vsync issue seems to be a rare quantum issue that magically disappears when being investigated more closely. I was able to determine that when my PC was playing music in the background (important: not using GPU audio), the rotation would lag and speed up when vsync is enabled, but only on my 165Hz monitor, not on the 60Hz monitor. I have never been that confused while investigating an issue. Rip my life wasted 30min on that...
